#!/bin/bash
CWD="`pwd`";

if [ "$#" -ne "1" ]
then
	echo "1 host parameters required"
	exit 1
fi
host2=$(($1+1)) 
host3=$(($1+2)) 
host4=$(($1+3))
#Kill URL shortner
for host in $1 $host2 $host3 $host4 
do
	ssh dh2026pc$host.utm.utoronto.ca "cd \"$CWD\"; kill `cat out/service$host.pid`;"
	echo $host
done
#Kill db Controller
for host in $1 $host2 $host3 $host4
do
	ssh dh2026pc$host.utm.utoronto.ca "cd \"$CWD\"; kill `cat out/dbcontroller$host.pid`;"
	echo $host
done
#kill Proxy
for host in $1
do
	ssh dh2026pc$host.utm.utoronto.ca "cd \"$CWD\"; kill `cat out/proxyService$host.pid`;"
	echo $host
done
